### ISSUE TITLE
Docker build fail

### ISSUE THREAD

**Issue by nickarouse** [Illumina/witty.er#12]
Docker build fails due to "Breaking Change: .NET Docker Repo Name Change #2375"

After updating the Docker file and building successfully I received the below error when running:
Failed to load , error: libunwind.so.8: cannot open shared object file: No such file or directory
Failed to bind to CoreCLR at '/opt/Wittyer/libcoreclr.so'

This was fixed with adding "apt-get -y install libunwind-dev" to the Docker file.

**Comment by Kentalot** [comment]
Thanks opened PR.
