### ISSUE TITLE
Missing SVTYPE info in base vcf

### ISSUE THREAD

**Issue by valeandri** [Illumina/witty.er#23]
Hi,

I am using witty.er on GIAB SV dataset and the tool gives me this exception:
```
Unhandled Exception: System.IO.InvalidDataException: Following variant does not have SVTYPE info key:
chr1	964542	HG3_Ill_SVrefine2DISCOVARDovetail_2	GGCTGCGGGGAGGGGGGCGCGGGTCCGCAGTGGGGCTGTGGGAGGGGTCCGCGCGTCCGCAGTGGGGATGT	G	20	PASS	.	GT:GTcons1:PB_GT:PB_REF:PB_ALT:PBHP_GT:PB_REF_HP1:PB_ALT_HP1:PB_REF_HP2:PB_ALT_HP2:TenX_GT:TenX_REF_HP1:TenX_ALT_HP1:TenX_REF_HP2:TenX_ALT_HP2:ILL250bp_GT:ILL250bp_REF:ILL250bp_ALT:ILLMP_GT:ILLMP_REF:ILLMP_ALT:BNG_LEN_DEL:BNG_LEN_INS:nabsys_svm	1/1:1/1:1/1:3:52:1/1:2:12:0:9:./.:1:0:5:0:0/0:8:0:./.:.:.:.:.:.
   at Ilmn.Das.Core.Tries.Extensions.Try.GetOrThrow[TSource](ITry`1 source)
   at Wittyer.Program.LaunchWittyerMain(String[] args) in /src/Wittyer/Program.cs:line 49
   at Wittyer.Program.Main(String[] args) in /src/Wittyer/Program.cs:line 22
```
I am using witty.er 0.3.5.1 built as docker image.

Thanks,
Valentina

**Comment by Kentalot** [comment]
please use this branch.  I will be deploying a few new versions soon though as well.  But for now, this will get you past it: https://github.com/Illumina/witty.er/tree/Kentalot-patch-1

**Comment by Kentalot** [comment]
I have pushed a major update to master, please use that branch instead now.  Dockerfile has changed.  There's a bunch of major new features but the README is still in the process of being updated but the normal behavior is still there as well, so you should be able to use it as is.  You can run --help to see the new options.

**Comment by valeandri** [comment]
Thanks @Kentalot, now it is working!

I'll close the issue.

Have a nice day and thanks for the tool.
